package lecho.lib.hellocharts.formatter

import lecho.lib.hellocharts.model.AxisValue

@Suppress("unused")
open class SimpleAxisValueFormatter() : AxisValueFormatter {
    private val valueFormatterHelper = ValueFormatterHelper()

    init {
        valueFormatterHelper.determineDecimalSeparator()
    }

    constructor(decimalDigitsNumber: Int) : this() {
        valueFormatterHelper.decimalDigitsNumber = decimalDigitsNumber
    }

    override fun formatValueForManualAxis(formattedValue: CharArray, axisValue: AxisValue): Int {
        return valueFormatterHelper.formatFloatValueWithPrependedAndAppendedText(
            formattedValue,
            axisValue.value, axisValue.labelAsChars
        )
    }

    override fun formatValueForAutoGeneratedAxis(
        formattedValue: CharArray,
        value: Float,
        autoDecimalDigits: Int
    ): Int {
        return valueFormatterHelper.formatFloatValueWithPrependedAndAppendedText(
            formattedValue,
            value, autoDecimalDigits
        )
    }

    val decimalDigitsNumber: Int
        get() = valueFormatterHelper.decimalDigitsNumber

    fun setDecimalDigitsNumber(decimalDigitsNumber: Int): SimpleAxisValueFormatter {
        valueFormatterHelper.decimalDigitsNumber = decimalDigitsNumber
        return this
    }

    val appendedText: CharArray
        get() = valueFormatterHelper.appendedText

    fun setAppendedText(appendedText: CharArray): SimpleAxisValueFormatter {
        valueFormatterHelper.appendedText = appendedText
        return this
    }

    val prependedText: CharArray
        get() = valueFormatterHelper.prependedText

    fun setPrependedText(prependedText: CharArray): SimpleAxisValueFormatter {
        valueFormatterHelper.prependedText = prependedText
        return this
    }

    val decimalSeparator: Char
        get() = valueFormatterHelper.decimalSeparator

    fun setDecimalSeparator(decimalSeparator: Char): SimpleAxisValueFormatter {
        valueFormatterHelper.decimalSeparator = decimalSeparator
        return this
    }
}